

defaults:
  - _self_
  - dataset: sat_gpm_f18

hydra:
  run:
    dir: outputs/${separate_folder}/${cfm_used}_${si_gamma_fn}_${si_gamma_a}/${seed}/${extra}

extra: "_"
separate_folder: "_"


ckpt_path: ""

num_nodes: 1
num_devices: 1
num_workers: 3
deterministic: true
torch_compile: 0

seed: 1999
trainer_precision: 32

model_used: "dit"
model_used_choices: ["unet", "dit"]


_it:
  depth: 8
  hidden_size: 384
  num_heads: 8
  patch_size: 4
  label_emb_noise_amplitude: 1.0



debug: 0
skip_to_test: 0
save_every_k_epochs: 10

nfe: 1
solver: "dopri5"
cfm_used: "cfm"
cdm_used_choices: ["cfm", "cfm_d2d", "si", "si_cos_sq"]

si_gamma_fn: "sqrt_t_times_1_sub_t"
si_gamma_fn_arr: ["sqrt_t_times_1_sub_t"]
si_gamma_a: 2
logit_normal_mu: -0.4
logit_normal_sigma: 0.0

n_epochs: 50
ema_epoch_start: 25
ema_decay: 0.9995

batch_size: 5
k_crops: 16
lr: 1.0e-4
warmup_steps: 1000



noise_type: "gaussian"
noise_type_choices_arr: ["gaussian"]

cond_used: "cfg"
cond_used_choices: ["vanilla", "cfg"]
class_dropout_prob: 0.1

cfg_scale: 1.0
do_stochastic_noising: 0


num_channels: 64
num_res_blocks: 2
channel_mult: [1, 1, 2, 3, 4]
attention_resolutions: "16"



time_sampler: "uniform"
timple_sampler_arr: ["uniform", "logit_normal"]


logit_normal_mu_t: -0.8
logit_normal_std_t: 0.0
noise_std: 1.0


 














